version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/src/c_two/_native"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      rust-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
