[package]
name = "c2-server"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description = "Tokio-based UDS server for C-Two IPC transport"

[dependencies]
c2-config = { version = "0.1.0", path = "../../foundation/c2-config" }
c2-error = { version = "0.1.0", path = "../../foundation/c2-error" }
c2-contract = { version = "0.1.0", path = "../../foundation/c2-contract" }
c2-wire = { version = "0.1.0", path = "../../protocol/c2-wire" }
c2-mem = { version = "0.1.0", path = "../../foundation/c2-mem" }
parking_lot = { workspace = true }
tokio = { version = "1", features = ["net", "rt-multi-thread", "sync", "macros", "io-util", "time"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
