//! SDK code generation for validated C-Two contract descriptors.

use serde_json::{Map, Value};
use std::collections::BTreeMap;
use thiserror::Error;

const CONTROL_JSON_CODEC_ID: &str = "c-two.control.json";
const GENERATED_HEADER: &str = "/* Generated by c3 contract codegen typescript. */";

#[derive(Debug, Clone, Default)]
pub struct TypeScriptOptions {
    pub strict_codecs: bool,
}

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error(transparent)]
    Contract(#[from] c2_contract::ContractError),
    #[error("contract descriptor must be valid JSON: {0}")]
    InvalidJson(String),
    #[error("contract descriptor invalid at {path}: {message}")]
    InvalidDescriptor { path: String, message: String },
    #[error(
        "unsupported codec {id}; provide a TypeScript codec provider or rerun without strict codec mode to emit opaque requirements"
    )]
    UnsupportedCodec { id: String },
}

pub fn generate_typescript_client(
    descriptor_json: &[u8],
    options: TypeScriptOptions,
) -> Result<String, CodegenError> {
    c2_contract::validate_portable_contract_descriptor_json(descriptor_json)?;
    let value: Value = serde_json::from_slice(descriptor_json)
        .map_err(|err| CodegenError::InvalidJson(err.to_string()))?;
    let digest = c2_contract::contract_descriptor_sha256_hex(descriptor_json)?;
    let root = object_at(&value, "$")?;
    let crm = object_at(required(root, "$", "crm")?, "$.crm")?;
    let crm_name = string_at(required(crm, "$.crm", "name")?, "$.crm.name")?;
    let methods = array_at(required(root, "$", "methods")?, "$.methods")?;
    let requirements = collect_codec_requirements(methods)?;
    if options.strict_codecs {
        if let Some(codec) = requirements.values().next() {
            return Err(CodegenError::UnsupportedCodec {
                id: codec_id(codec)?.to_string(),
            });
        }
    }

    let const_prefix = const_identifier(crm_name);
    let class_name = format!("{}Client", pascal_identifier(crm_name));
    let mut output = String::new();
    output.push_str(GENERATED_HEADER);
    output.push_str("\n\n");
    render_support_types(&mut output);
    render_contract_const(&mut output, &const_prefix, crm, &digest)?;
    render_codec_requirements(&mut output, &const_prefix, &requirements)?;
    render_codec_stubs(&mut output, &const_prefix, &requirements);
    render_client_class(&mut output, &class_name, &const_prefix, methods)?;
    render_helpers(&mut output);
    Ok(output)
}

fn render_support_types(output: &mut String) {
    output.push_str(
        r#"export interface C2ContractIdentity {
  readonly schema: "c-two.contract.v1";
  readonly namespace: string;
  readonly name: string;
  readonly version: string;
  readonly sha256: string;
}

export interface C2ClientTransport {
  call<T>(routeName: string, contract: C2ContractIdentity, method: string, args: readonly unknown[]): Promise<T>;
}

export type C2CodecValue<CodecId extends string> = {
  readonly codecId: CodecId;
  readonly value: unknown;
};

export interface C2CodecRequirement {
  readonly id: string;
  readonly version: string;
  readonly schema?: string;
  readonly schemaSha256?: string;
  readonly mediaType?: string;
  readonly capabilities: readonly string[];
}

export interface C2CodecImplementation<CodecId extends string = string> {
  readonly id: CodecId;
  readonly requirement: C2CodecRequirement;
  encode(value: unknown): Uint8Array | Promise<Uint8Array>;
  decode(data: Uint8Array): unknown | Promise<unknown>;
  fromBuffer?(data: Uint8Array): unknown | Promise<unknown>;
}

export type C2CodecRegistry = Readonly<Record<string, C2CodecImplementation<string>>>;

"#,
    );
}

fn render_contract_const(
    output: &mut String,
    const_prefix: &str,
    crm: &Map<String, Value>,
    digest: &str,
) -> Result<(), CodegenError> {
    let namespace = string_at(required(crm, "$.crm", "namespace")?, "$.crm.namespace")?;
    let name = string_at(required(crm, "$.crm", "name")?, "$.crm.name")?;
    let version = string_at(required(crm, "$.crm", "version")?, "$.crm.version")?;
    output.push_str(&format!(
        "export const {const_prefix}_CONTRACT: C2ContractIdentity = {{\n  schema: \"c-two.contract.v1\",\n  namespace: {},\n  name: {},\n  version: {},\n  sha256: {},\n}};\n\n",
        ts_string(namespace),
        ts_string(name),
        ts_string(version),
        ts_string(digest),
    ));
    Ok(())
}

fn render_codec_requirements(
    output: &mut String,
    const_prefix: &str,
    requirements: &BTreeMap<String, Value>,
) -> Result<(), CodegenError> {
    output.push_str(&format!(
        "export const {const_prefix}_CODEC_REQUIREMENTS: readonly C2CodecRequirement[] = "
    ));
    if requirements.is_empty() {
        output.push_str("[];\n\n");
        return Ok(());
    }
    output.push_str("[\n");
    for codec in requirements.values() {
        output.push_str("  {\n");
        output.push_str(&format!("    id: {},\n", ts_string(codec_id(codec)?)));
        output.push_str(&format!(
            "    version: {},\n",
            ts_string(optional_string(codec, "version").unwrap_or(""))
        ));
        if let Some(schema) = optional_string(codec, "schema") {
            output.push_str(&format!("    schema: {},\n", ts_string(schema)));
        }
        if let Some(schema_sha256) = optional_string(codec, "schema_sha256") {
            output.push_str(&format!(
                "    schemaSha256: {},\n",
                ts_string(schema_sha256)
            ));
        }
        if let Some(media_type) = optional_string(codec, "media_type") {
            output.push_str(&format!("    mediaType: {},\n", ts_string(media_type)));
        }
        output.push_str("    capabilities: [");
        let capabilities = codec
            .get("capabilities")
            .and_then(Value::as_array)
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        for (index, item) in capabilities.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&ts_string(item.as_str().unwrap_or("")));
        }
        output.push_str("],\n  },\n");
    }
    output.push_str("];\n\n");
    Ok(())
}

fn render_codec_stubs(
    output: &mut String,
    const_prefix: &str,
    requirements: &BTreeMap<String, Value>,
) {
    if requirements.is_empty() {
        return;
    }
    output.push_str(&format!(
        "export function createCodecStubs(): C2CodecRegistry {{\n  const registry: Record<string, C2CodecImplementation<string>> = {{}};\n  for (const requirement of {const_prefix}_CODEC_REQUIREMENTS) {{\n    registry[requirement.id] = {{\n      id: requirement.id,\n      requirement,\n      encode(_value: unknown): Uint8Array {{\n        throw missingCodecImplementation(requirement);\n      }},\n      decode(_data: Uint8Array): unknown {{\n        throw missingCodecImplementation(requirement);\n      }},\n      fromBuffer(_data: Uint8Array): unknown {{\n        throw missingCodecImplementation(requirement);\n      }},\n    }};\n  }}\n  return registry;\n}}\n\n"
    ));
}

fn render_client_class(
    output: &mut String,
    class_name: &str,
    const_prefix: &str,
    methods: &[Value],
) -> Result<(), CodegenError> {
    output.push_str(&format!(
        "export class {class_name} {{\n  constructor(private readonly transport: C2ClientTransport, private readonly routeName: string) {{}}\n\n"
    ));
    let mut method_identifiers = BTreeMap::new();
    for method in methods {
        let method_obj = object_at(method, "$.methods[]")?;
        let method_name = string_at(
            required(method_obj, "$.methods[]", "name")?,
            "$.methods[].name",
        )?;
        let method_ident = member_identifier(method_name);
        if let Some(previous) = method_identifiers.insert(method_ident.clone(), method_name) {
            return Err(CodegenError::InvalidDescriptor {
                path: "$.methods".to_string(),
                message: format!(
                    "method name collision after TypeScript identifier sanitization: {previous:?} and {method_name:?} both map to {method_ident:?}"
                ),
            });
        }
        let params = array_at(
            required(method_obj, "$.methods[]", "parameters")?,
            "$.methods[].parameters",
        )?;
        let return_type = return_type(required(method_obj, "$.methods[]", "return")?)?;
        let rendered_params = render_parameters(params)?;
        let arg_list = rendered_params.arg_identifiers.join(", ");
        let args_expr = if arg_list.is_empty() {
            "[]".to_string()
        } else {
            format!("compactTrailingUndefined([{arg_list}])")
        };
        output.push_str(&format!(
            "  async {method_ident}({}): Promise<{return_type}> {{\n    return this.transport.call<{return_type}>(\n      this.routeName,\n      {const_prefix}_CONTRACT,\n      {},\n      {args_expr},\n    );\n  }}\n\n",
            rendered_params.signature,
            ts_string(method_name),
        ));
    }
    output.push_str("}\n\n");
    Ok(())
}

struct RenderedParameters {
    signature: String,
    arg_identifiers: Vec<String>,
}

fn render_parameters(params: &[Value]) -> Result<RenderedParameters, CodegenError> {
    let mut identifiers = BTreeMap::new();
    let mut signature = Vec::new();
    let mut arg_identifiers = Vec::new();
    for param in params {
        let param_obj = object_at(param, "$.methods[].parameters[]")?;
        let original_name = string_at(
            required(param_obj, "$.methods[].parameters[]", "name")?,
            "$.methods[].parameters[].name",
        )?;
        let name = identifier(original_name);
        if let Some(previous) = identifiers.insert(name.clone(), original_name) {
            return Err(CodegenError::InvalidDescriptor {
                path: "$.methods[].parameters".to_string(),
                message: format!(
                    "parameter name collision after TypeScript identifier sanitization: {previous:?} and {original_name:?} both map to {name:?}"
                ),
            });
        }
        let default = object_at(
            required(param_obj, "$.methods[].parameters[]", "default")?,
            "$.methods[].parameters[].default",
        )?;
        let optional = string_at(
            required(default, "$.methods[].parameters[].default", "kind")?,
            "$.methods[].parameters[].default.kind",
        )? != "missing";
        let type_name = annotation_type(required(param_obj, "$.methods[].parameters[]", "type")?)?;
        signature.push(format!(
            "{name}{}: {type_name}",
            if optional { "?" } else { "" }
        ));
        arg_identifiers.push(name);
    }
    Ok(RenderedParameters {
        signature: signature.join(", "),
        arg_identifiers,
    })
}

fn render_helpers(output: &mut String) {
    output.push_str(
        r#"function compactTrailingUndefined(values: unknown[]): unknown[] {
  let end = values.length;
  while (end > 0 && values[end - 1] === undefined) {
    end -= 1;
  }
  return values.slice(0, end);
}

function missingCodecImplementation(requirement: C2CodecRequirement): Error {
  return new Error(`Codec ${requirement.id} requires application runtime implementation.`);
}
"#,
    );
}

fn return_type(annotation: &Value) -> Result<String, CodegenError> {
    let object = object_at(annotation, "$.methods[].return")?;
    if string_at(
        required(object, "$.methods[].return", "kind")?,
        "$.methods[].return.kind",
    )? == "none"
    {
        return Ok("void".to_string());
    }
    annotation_type(annotation)
}

fn annotation_type(annotation: &Value) -> Result<String, CodegenError> {
    let object = object_at(annotation, "$.annotation")?;
    let kind = string_at(
        required(object, "$.annotation", "kind")?,
        "$.annotation.kind",
    )?;
    match kind {
        "none" => Ok("null".to_string()),
        "primitive" => primitive_type(string_at(
            required(object, "$.annotation", "name")?,
            "$.annotation.name",
        )?),
        "list" => {
            let item = annotation_type(required(object, "$.annotation", "item")?)?;
            if item.contains(" | ") {
                Ok(format!("Array<{item}>"))
            } else {
                Ok(format!("{item}[]"))
            }
        }
        "dict" => {
            let value = annotation_type(required(object, "$.annotation", "value")?)?;
            Ok(format!("Record<string, {value}>"))
        }
        "tuple" => {
            let items = array_at(
                required(object, "$.annotation", "items")?,
                "$.annotation.items",
            )?
            .iter()
            .map(annotation_type)
            .collect::<Result<Vec<_>, _>>()?;
            Ok(format!("[{}]", items.join(", ")))
        }
        "tuple_variadic" => {
            let item = annotation_type(required(object, "$.annotation", "item")?)?;
            Ok(format!("Array<{item}>"))
        }
        "union" => {
            let items = array_at(
                required(object, "$.annotation", "items")?,
                "$.annotation.items",
            )?
            .iter()
            .map(annotation_type)
            .collect::<Result<Vec<_>, _>>()?;
            Ok(items.join(" | "))
        }
        "codec" => codec_value_type(required(object, "$.annotation", "codec")?),
        "transferable" => codec_value_type(required(object, "$.annotation", "abi_ref")?),
        _ => Ok("unknown".to_string()),
    }
}

fn primitive_type(name: &str) -> Result<String, CodegenError> {
    match name {
        "bool" => Ok("boolean".to_string()),
        "int" | "float" => Ok("number".to_string()),
        "str" => Ok("string".to_string()),
        "bytes" | "memoryview" | "bytearray" => Ok("Uint8Array".to_string()),
        other => Err(CodegenError::InvalidDescriptor {
            path: "$.annotation.name".to_string(),
            message: format!("unsupported primitive {other:?}"),
        }),
    }
}

fn codec_value_type(codec: &Value) -> Result<String, CodegenError> {
    Ok(format!("C2CodecValue<{}>", ts_string(codec_id(codec)?)))
}

fn collect_codec_requirements(methods: &[Value]) -> Result<BTreeMap<String, Value>, CodegenError> {
    let mut requirements = BTreeMap::new();
    for method in methods {
        let method_obj = object_at(method, "$.methods[]")?;
        let wire = object_at(
            required(method_obj, "$.methods[]", "wire")?,
            "$.methods[].wire",
        )?;
        for field in ["input", "output"] {
            let Some(codec) = wire.get(field) else {
                continue;
            };
            if codec.is_null() {
                continue;
            }
            let codec_id = codec_id(codec)?;
            if codec_id != CONTROL_JSON_CODEC_ID {
                requirements.insert(codec_key(codec), codec.clone());
            }
        }
    }
    Ok(requirements)
}

fn codec_key(codec: &Value) -> String {
    serde_json::to_string(codec).unwrap_or_else(|_| String::new())
}

fn codec_id(codec: &Value) -> Result<&str, CodegenError> {
    let object = object_at(codec, "$.codec_ref")?;
    string_at(required(object, "$.codec_ref", "id")?, "$.codec_ref.id")
}

fn required<'a>(
    object: &'a Map<String, Value>,
    path: &str,
    key: &str,
) -> Result<&'a Value, CodegenError> {
    object
        .get(key)
        .ok_or_else(|| CodegenError::InvalidDescriptor {
            path: path.to_string(),
            message: format!("missing key {key:?}"),
        })
}

fn object_at<'a>(value: &'a Value, path: &str) -> Result<&'a Map<String, Value>, CodegenError> {
    value
        .as_object()
        .ok_or_else(|| CodegenError::InvalidDescriptor {
            path: path.to_string(),
            message: "expected object".to_string(),
        })
}

fn array_at<'a>(value: &'a Value, path: &str) -> Result<&'a [Value], CodegenError> {
    value
        .as_array()
        .map(Vec::as_slice)
        .ok_or_else(|| CodegenError::InvalidDescriptor {
            path: path.to_string(),
            message: "expected array".to_string(),
        })
}

fn string_at<'a>(value: &'a Value, path: &str) -> Result<&'a str, CodegenError> {
    value
        .as_str()
        .ok_or_else(|| CodegenError::InvalidDescriptor {
            path: path.to_string(),
            message: "expected string".to_string(),
        })
}

fn optional_string<'a>(value: &'a Value, key: &str) -> Option<&'a str> {
    value.get(key).and_then(Value::as_str)
}

fn ts_string(value: &str) -> String {
    serde_json::to_string(value).expect("string literal serialization cannot fail")
}

fn pascal_identifier(value: &str) -> String {
    let ident = identifier(value);
    let mut chars = ident.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => "Contract".to_string(),
    }
}

fn const_identifier(value: &str) -> String {
    let mut result = String::new();
    let mut previous_lower_or_digit = false;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && previous_lower_or_digit && !result.ends_with('_') {
                result.push('_');
            }
            result.push(ch.to_ascii_uppercase());
            previous_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        } else if !result.ends_with('_') {
            result.push('_');
            previous_lower_or_digit = false;
        }
    }
    let result = result.trim_matches('_').to_string();
    if result.is_empty() {
        "CONTRACT".to_string()
    } else if result.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("_{result}")
    } else {
        result
    }
}

fn member_identifier(value: &str) -> String {
    identifier(value)
}

fn identifier(value: &str) -> String {
    let mut result = String::new();
    for (index, ch) in value.chars().enumerate() {
        let valid = ch == '_' || ch == '$' || ch.is_ascii_alphanumeric();
        if !valid {
            result.push('_');
            continue;
        }
        if index == 0 && ch.is_ascii_digit() {
            result.push('_');
        }
        result.push(ch);
    }
    if result.is_empty() {
        result.push('_');
    }
    if is_ts_reserved(&result) {
        result.push('_');
    }
    result
}

fn is_ts_reserved(value: &str) -> bool {
    matches!(
        value,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "debugger"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "export"
            | "extends"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
    )
}
