[package]
name = "c2-local"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description = "Local endpoints and asynchronous operating-system streams for C-Two"

[dependencies]
c2-config = { version = "0.1.0", path = "../../foundation/c2-config" }
tokio = { version = "1", features = ["net", "rt", "sync", "macros", "io-util", "time"] }
futures-util = "0.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
socket2 = "0.6"

[target.'cfg(windows)'.dependencies]
c2-local-security = { version = "0.1.0", path = "../../foundation/c2-local-security" }
sha2 = "0.10"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_IO", "Win32_System_Threading"] }
